"use client";
import {useEffect,useState} from "react";
import {AppShell} from "@/components/AppShell";
export default function Submit(){
 const[artist,setArtist]=useState(""),[clue,setClue]=useState(""),[url,setUrl]=useState(""),[image,setImage]=useState(""),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState("");
 useEffect(()=>setArtist(new URLSearchParams(location.search).get("q")||""),[]);
 async function save(){setBusy(true);setError("");try{const r=await fetch("/api/submissions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({artistName:artist,clue,sourceUrl:url||undefined,image:image||undefined})});if(!r.ok)throw new Error((await r.json()).error||"提交失败，请稍后重试");setDone(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const ready=artist.trim()&&Boolean(clue.trim()||url.trim()||image);
 return <AppShell><h1 className="page-title">告诉我们这次回归</h1><p className="lead">你只需提供线索，系统会自动搜索、核实和整理。</p>{done?<div className="empty card">已收到，我们会自动核实相关回归信息。</div>:<div className="form-card card">{error&&<div className="notice error" role="alert">{error}</div>}<div className="field"><label>艺人 / 组合名称 *</label><input value={artist} maxLength={200} onChange={e=>setArtist(e.target.value)} placeholder="例如：NCT WISH"/></div><div className="field"><label>文字线索</label><textarea value={clue} maxLength={10000} onChange={e=>setClue(e.target.value)} placeholder="例如：听说10月回归"/></div><div className="field"><label>来源链接</label><input value={url} maxLength={2000} onChange={e=>setUrl(e.target.value)} placeholder="微博 / X / Instagram / Weverse 等链接"/></div><div className="field"><label>上传截图（PNG/JPEG，最多 2 MB）</label><input type="file" accept="image/png,image/jpeg" onChange={e=>{const file=e.target.files?.[0];setImage("");if(!file)return;if(file.size>2*1024*1024||!["image/png","image/jpeg"].includes(file.type)){setError("请选择不超过 2 MB 的 PNG 或 JPEG");return}const reader=new FileReader();reader.onload=()=>setImage(String(reader.result));reader.readAsDataURL(file)}}/>{image&&<p className="eyebrow">截图已添加，系统会尝试识别其中的信息。</p>}</div><button className="primary wide" disabled={busy||!ready} onClick={save}>{busy?"正在提交并自动核实…":"提交线索"}</button></div>}</AppShell>
}
