"use client";
import {useEffect,useState} from "react";
import {AppShell} from "@/components/AppShell";
export default function Submit(){
 const[raw,setRaw]=useState(""),[artist,setArtist]=useState(""),[album,setAlbum]=useState(""),[date,setDate]=useState(""),[url,setUrl]=useState(""),[image,setImage]=useState(""),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState("");
 useEffect(()=>{setArtist(new URLSearchParams(location.search).get("q")||"")},[]);
 async function extract(){setBusy(true);try{const r=await fetch("/api/submissions/extract",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({content:[artist,album,date,url,raw].join("\n")})});const result=await r.json();const extracted=result.data||{};if(!artist&&typeof extracted.artistName==="string")setArtist(extracted.artistName);if(!album&&typeof extracted.albumName==="string")setAlbum(extracted.albumName);if(!date&&typeof extracted.releaseDate==="string")setDate(extracted.releaseDate);if(!r.ok)setError("自动提取暂不可用，请手动核对字段");setConfirmed(true)}catch{setConfirmed(true);setError("可手动核对并提交")}finally{setBusy(false)}}
 async function save(){setBusy(true);setError("");try{const r=await fetch("/api/submissions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({sourceType:"MISSING_RELEASE",rawContent:raw||artist+" / "+album,extractedData:{artistName:artist,albumName:album,releaseDate:date,sourceUrl:url,image}})});if(!r.ok)throw new Error("提交未保存，请稍后重试");setDone(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <AppShell><h1 className="page-title">告诉我们这次回归</h1><p className="lead">提供专辑原名和公告线索，确认后进入核实队列。</p>{done?<div className="empty card">已收到，核实后收录。</div>:<div className="form-card card">{error&&<p role="alert">{error}</p>}{[["艺人名",artist,setArtist],["专辑原名",album,setAlbum],["发行日期（YYYY-MM-DD，未知可留空）",date,setDate],["来源链接",url,setUrl]].map(([label,value,setter])=><div className="field" key={String(label)}><label>{String(label)}</label><input value={String(value)} maxLength={500} onChange={e=>(setter as (s:string)=>void)(e.target.value)}/></div>)}<div className="field"><label>公告文字</label><textarea maxLength={10000} value={raw} onChange={e=>setRaw(e.target.value)}/></div><div className="field"><label>上传截图（PNG/JPEG，最多 2 MB）</label><input type="file" accept="image/png,image/jpeg" onChange={e=>{const file=e.target.files?.[0];setImage("");if(!file)return;if(file.size>2*1024*1024||!["image/png","image/jpeg"].includes(file.type)){setError("请选择不超过 2 MB 的 PNG 或 JPEG");return}const reader=new FileReader();reader.onload=()=>setImage(String(reader.result));reader.readAsDataURL(file)}}/>{image&&<p>截图将在提交后保存供人工核实。请将关键文字填入上方。</p>}</div><button className="secondary wide" disabled={busy||!artist} onClick={extract}>提取并检查信息</button>{confirmed&&<><div className="notice">请核对上方字段。截图仅作核实证据，当前不会自动识别图片文字。</div><button className="primary wide" disabled={busy||!artist||!album} onClick={save}>确认并提交核实</button></>}</div>}</AppShell>
}
