import {createHash} from "node:crypto";
import {prisma} from "./prisma";

export type OfferInput={source:string;sourceUrl?:string;capturedAt?:string;content:string;changeType?:string;albumId?:string;image?:string;trustedCapture?:boolean};
type ExtractedOffer={artist?:string;album?:string;version?:string;price?:number;currency?:string;benefits?:string[];saleType?:string;deadline?:string;confidence:number};
const trustedDefaults=["ktown4u.com","weverse.io","shop.weverse.io"];
function hostname(url?:string){try{return new URL(url||"").hostname.toLowerCase().replace(/^www\./,"")}catch{return""}}
function sourceTrust(url:string|undefined,stored?:string){if(stored&&stored!=="UNKNOWN")return stored;const configured=(process.env.TRUSTED_OFFER_HOSTS||"").split(",").map(v=>v.trim().toLowerCase()).filter(Boolean);const host=hostname(url);return[...trustedDefaults,...configured].some(v=>host===v||host.endsWith(`.${v}`))?"TRUSTED":"UNKNOWN"}
function ruleExtract(input:OfferInput):ExtractedOffer{const content=input.content||"";const price=content.match(/(?:¥|￥|CNY|RMB)\s*([0-9]+(?:\.[0-9]{1,2})?)|([0-9]+(?:\.[0-9]{1,2})?)\s*(?:元|CNY|RMB)/i);const currency=/\b(?:USD|US\$|\$)\b/i.test(content)?"USD":/₩|KRW/i.test(content)?"KRW":"CNY";return{price:Number(price?.[1]||price?.[2])||undefined,currency,version:content.match(/(?:版本|version)[:：\s]*([^\n,，]{1,80})/i)?.[1]?.trim(),benefits:[...content.matchAll(/(?:POB|特典|小卡)[:：\s]*([^\n]{1,100})/gi)].map(v=>v[1].trim()),saleType:/团购|大吧/.test(content)?"GROUP_ORDER":"RETAIL",deadline:content.match(/(?:截止|deadline)[:：\s]*(\d{4}-\d{2}-\d{2})/i)?.[1],confidence:price?.[0]?0.72:0.25}}
async function llmExtract(input:OfferInput):Promise<ExtractedOffer|null>{if(process.env.AI_PROVIDER!=="llm"||!process.env.AI_API_KEY||!process.env.AI_BASE_URL||!process.env.AI_MODEL)return null;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(`${process.env.AI_BASE_URL.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${process.env.AI_API_KEY}`},body:JSON.stringify({model:process.env.AI_MODEL,temperature:0,response_format:{type:"json_object"},messages:[{role:"system",content:"只从用户提供的购买信息中抽取 JSON：artist, album, version, price, currency, benefits(数组), saleType, deadline(YYYY-MM-DD), confidence(0-1)。缺失字段省略，禁止猜测价格、日期和商品事实。"},{role:"user",content:`来源：${input.source}\n链接：${input.sourceUrl||""}\n内容：${input.content}`}]}),signal:controller.signal});if(!response.ok)return null;const body=await response.json() as {choices?:Array<{message?:{content?:string}}>};const value=JSON.parse(body.choices?.[0]?.message?.content||"null");return value&&typeof value==="object"?value:null}catch{return null}finally{clearTimeout(timer)}}
function fingerprint(albumId:string,source:string,version:string,url:string){return createHash("sha256").update([albumId,source.toLowerCase(),version.toLowerCase(),url].join("|")).digest("hex")}

export class OfferPipeline{
 async ingest(input:OfferInput){
  const extracted=(await llmExtract(input))||ruleExtract(input);let album=input.albumId?await prisma.album.findUnique({where:{id:input.albumId},include:{artist:true,group:true}}):null;
  if(!album&&extracted.album)album=await prisma.album.findFirst({where:{title:{contains:extracted.album,mode:"insensitive"}},include:{artist:true,group:true}});
  const source=await prisma.source.upsert({where:{id:`offer-${createHash("sha1").update(input.source+hostname(input.sourceUrl)).digest("hex").slice(0,24)}`},update:{url:input.sourceUrl||undefined},create:{id:`offer-${createHash("sha1").update(input.source+hostname(input.sourceUrl)).digest("hex").slice(0,24)}`,name:input.source,type:"PURCHASE_CHANNEL",url:input.sourceUrl}});
  const trust=input.trustedCapture?sourceTrust(input.sourceUrl,source.trustLevel):"UNKNOWN",reasons:string[]=[];if(!input.trustedCapture)reasons.push("用户线索待自动核实");if(!album)reasons.push("无法匹配专辑");if(!extracted.price||extracted.price<=0)reasons.push("未识别有效价格");if(extracted.confidence<0.65)reasons.push("AI/规则置信度较低");if(trust==="UNKNOWN")reasons.push("未知来源");if(extracted.price&&extracted.price>100000)reasons.push("价格异常");
  if(!album){const exception=await prisma.offerException.create({data:{reason:reasons.join("；"),rawPayload:JSON.stringify(input)}});return{offerId:null,exceptionId:exception.id,status:"PENDING_EXCEPTION" as const,reasons,albumId:null}}
  const target=album;
  let version=await prisma.albumVersion.findFirst({where:{albumId:target.id,name:{equals:extracted.version||"待确认版本",mode:"insensitive"}}});if(!version)version=await prisma.albumVersion.create({data:{albumId:target.id,name:extracted.version||"待确认版本",packageType:"待确认"}});
  const channel=await prisma.channel.upsert({where:{name:input.source},update:{platform:hostname(input.sourceUrl)||input.source},create:{name:input.source,platform:hostname(input.sourceUrl)||input.source,region:"待确认"}});
  const key=fingerprint(target.id,input.source,version.name,input.sourceUrl||"");const pending=reasons.length>0;const offer=await prisma.purchaseOffer.upsert({where:{fingerprint:key},update:{productPrice:extracted.price||0,currency:extracted.currency||"CNY",saleType:extracted.saleType||"RETAIL",deadline:extracted.deadline?new Date(`${extracted.deadline}T00:00:00Z`):null,inclusions:JSON.stringify(extracted.benefits||[]),evidence:JSON.stringify({sourceUrl:input.sourceUrl,capturedAt:input.capturedAt||new Date().toISOString(),content:input.content.slice(0,5000),changeType:input.changeType}),confidence:extracted.confidence,status:pending?"PENDING_EXCEPTION":"VERIFIED",lastVerifiedAt:new Date()},create:{albumVersionId:version.id,channelId:channel.id,productPrice:extracted.price||0,currency:extracted.currency||"CNY",stockStatus:"UNKNOWN",saleType:extracted.saleType||"RETAIL",shippingOrigin:"待确认",deadline:extracted.deadline?new Date(`${extracted.deadline}T00:00:00Z`):null,memberSelectable:false,inclusions:JSON.stringify(extracted.benefits||[]),purchaseUrl:input.sourceUrl,sourceId:source.id,fingerprint:key,evidence:JSON.stringify({sourceUrl:input.sourceUrl,capturedAt:input.capturedAt||new Date().toISOString(),content:input.content.slice(0,5000),changeType:input.changeType}),confidence:extracted.confidence,status:pending?"PENDING_EXCEPTION":"VERIFIED",lastVerifiedAt:new Date()}});
  await prisma.priceHistory.create({data:{offerId:offer.id,price:offer.productPrice}});
  if(pending)await prisma.offerException.upsert({where:{offerId:offer.id},update:{reason:reasons.join("；"),rawPayload:JSON.stringify(input),status:"OPEN",reviewedAt:null},create:{offerId:offer.id,reason:reasons.join("；"),rawPayload:JSON.stringify(input)}});else await prisma.offerException.deleteMany({where:{offerId:offer.id}});
  await prisma.systemMetric.create({data:{metricName:"offer_ingestion",value:pending?0:1,unit:"status",metadata:JSON.stringify({source:input.source,pending})}}).catch(()=>{});
  return{offerId:offer.id,status:pending?"PENDING_EXCEPTION":"PUBLISHED",reasons,albumId:target.id};
 }
}
