import {createHash} from "node:crypto";
import {prisma} from "./prisma";

export type OfferInput={source:string;sourceUrl?:string;capturedAt?:string;content:string;changeType?:string;albumId?:string;image?:string;trustedCapture?:boolean};
type ExtractedOffer={artist?:string;album?:string;version?:string;price?:number;platformPrice?:number;currency?:string;benefits?:string[];saleType?:string;deadline?:string;platform?:string;offerSource?:string;confidence:number};
const trustedDefaults=["ktown4u.com","weverse.io","shop.weverse.io"];
function hostname(url?:string){try{return new URL(url||"").hostname.toLowerCase().replace(/^www\./,"")}catch{return""}}
function sourceTrust(url:string|undefined,stored?:string){if(stored&&stored!=="UNKNOWN")return stored;const configured=(process.env.TRUSTED_OFFER_HOSTS||"").split(",").map(v=>v.trim().toLowerCase()).filter(Boolean);const host=hostname(url);return[...trustedDefaults,...configured].some(v=>host===v||host.endsWith(`.${v}`))?"TRUSTED":"UNKNOWN"}
const platformNames=["Ktown4u","Weverse","星河","液体猫","Pinky"];
export function resolvePlatformHint(value:string){const lower=value.toLowerCase();return platformNames.find(name=>lower.includes(name.toLowerCase()))||null}
function ruleExtract(input:OfferInput):ExtractedOffer{const content=input.content||"";const price=content.match(/(?:价格[:：\s]*)?(?:¥|￥|CNY|RMB|USD|US\$|\$|KRW|₩)\s*([0-9]+(?:\.[0-9]{1,2})?)|(?:价格[:：\s]*)?([0-9]+(?:\.[0-9]{1,2})?)\s*(?:元|CNY|RMB|USD|US\$|\$|KRW|₩)/i);const platformPrice=content.match(/(?:平台(?:公开)?价|商城(?:公开)?价)[:：\s]*(?:¥|￥)?\s*([0-9]+(?:\.[0-9]{1,2})?)/i);const currency=/\b(?:USD|US\$)|\$/i.test(content)?"USD":/₩|KRW/i.test(content)?"KRW":"CNY";return{album:content.match(/(?:专辑|album)[:：\s]*([^\n,，]{1,120})/i)?.[1]?.trim(),artist:content.match(/(?:艺人|artist)[:：\s]*([^\n,，]{1,120})/i)?.[1]?.trim(),price:Number(price?.[1]||price?.[2])||undefined,platformPrice:Number(platformPrice?.[1])||undefined,currency,version:content.match(/(?:版本|version)[:：\s]*([^\n,，]{1,80})/i)?.[1]?.trim(),benefits:[...content.matchAll(/(?:POB|特典|小卡)[:：\s]*([^\n]{1,100})/gi)].map(v=>v[1].trim()),saleType:/团购|大吧/.test(`${input.source} ${content}`)?"GROUP_ORDER":"RETAIL",deadline:content.match(/(?:截止|deadline)[:：\s]*(\d{4}-\d{2}-\d{2})/i)?.[1],platform:resolvePlatformHint(`${input.source} ${content}`)||undefined,offerSource:input.source,confidence:price?.[0]?0.72:0.25}}
async function llmExtract(input:OfferInput):Promise<ExtractedOffer|null>{if(process.env.AI_PROVIDER!=="llm"||!process.env.AI_API_KEY||!process.env.AI_BASE_URL||!process.env.AI_MODEL)return null;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const prompt=`来源：${input.source}\n链接：${input.sourceUrl||""}\n内容：${input.content}`;const userContent=input.image?[{type:"text",text:prompt},{type:"image_url",image_url:{url:input.image}}]:prompt;const response=await fetch(`${process.env.AI_BASE_URL.replace(/\/$/,"")}/chat/completions`,{method:"POST",headers:{"content-type":"application/json",authorization:`Bearer ${process.env.AI_API_KEY}`},body:JSON.stringify({model:process.env.AI_MODEL,temperature:0,response_format:{type:"json_object"},messages:[{role:"system",content:"只从用户提供的购买信息或截图中抽取 JSON：artist, album, version, price, platformPrice, currency, benefits(数组), saleType, deadline(YYYY-MM-DD), platform, offerSource, confidence(0-1)。大吧团购价格放price，商城公开价放platformPrice；缺失字段省略，禁止猜测。"},{role:"user",content:userContent}]}),signal:controller.signal});if(!response.ok)return null;const body=await response.json() as {choices?:Array<{message?:{content?:string}}>};const value=JSON.parse(body.choices?.[0]?.message?.content||"null");return value&&typeof value==="object"?value:null}catch{return null}finally{clearTimeout(timer)}}
function searchTemplates(){try{return JSON.parse(process.env.OFFER_PLATFORM_SEARCH_URLS||"{}")as Record<string,string>}catch{return{}}}
async function searchPlatformProduct(platform:string|undefined,artist:string|undefined,album:string|undefined,version:string|undefined){const template=platform?searchTemplates()[platform]:undefined;if(!template||!album)return null;const query=[artist,album,version].filter(Boolean).join(" ");const url=template.replace("{query}",encodeURIComponent(query));const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),5000);try{const response=await fetch(url,{headers:{accept:"text/html,application/json","user-agent":"KPOP-PICK/1.0 (+https://www.myarea.website)"},signal:controller.signal});if(!response.ok)return null;const text=await response.text();const href=[...text.matchAll(/href=["']([^"']*(?:product|goods|item|sales)[^"']*)["']/gi)][0]?.[1];return href?new URL(href,url).toString():null}catch{return null}finally{clearTimeout(timer)}}
function fingerprint(albumId:string,source:string,version:string,url:string){return createHash("sha256").update([albumId,source.toLowerCase(),version.toLowerCase(),url].join("|")).digest("hex")}

export class OfferPipeline{
 async ingest(input:OfferInput){
  const extracted=(await llmExtract(input))||ruleExtract(input);let album=input.albumId?await prisma.album.findUnique({where:{id:input.albumId},include:{artist:true,group:true}}):null;
  if(!album&&extracted.album)album=await prisma.album.findFirst({where:{title:{contains:extracted.album,mode:"insensitive"}},include:{artist:true,group:true}});
  const source=await prisma.source.upsert({where:{id:`offer-${createHash("sha1").update(input.source+hostname(input.sourceUrl)).digest("hex").slice(0,24)}`},update:{url:input.sourceUrl||undefined},create:{id:`offer-${createHash("sha1").update(input.source+hostname(input.sourceUrl)).digest("hex").slice(0,24)}`,name:input.source,type:"PURCHASE_CHANNEL",url:input.sourceUrl}});
  const platform=extracted.platform||resolvePlatformHint(`${input.source} ${input.content}`)||undefined;const directProductUrl=input.sourceUrl&&sourceTrust(input.sourceUrl)!=="UNKNOWN"?input.sourceUrl:undefined;const platformProductUrl=directProductUrl||await searchPlatformProduct(platform,extracted.artist,extracted.album,extracted.version)||undefined;const trust=input.trustedCapture?sourceTrust(platformProductUrl,source.trustLevel):sourceTrust(platformProductUrl),reasons:string[]=[];if(!input.trustedCapture&&!platformProductUrl)reasons.push("用户线索尚未匹配公开商品");if(!album)reasons.push("无法匹配专辑");if(!extracted.price||extracted.price<=0)reasons.push("未识别有效价格");if(extracted.confidence<0.65)reasons.push("AI/规则置信度较低");if(trust==="UNKNOWN")reasons.push("未知来源");if(extracted.price&&extracted.price>100000)reasons.push("价格异常");
  if(!album){const exception=await prisma.offerException.create({data:{reason:reasons.join("；"),rawPayload:JSON.stringify(input)}});return{offerId:null,exceptionId:exception.id,status:"PENDING_EXCEPTION" as const,reasons,albumId:null}}
  const target=album;
  let version=await prisma.albumVersion.findFirst({where:{albumId:target.id,name:{equals:extracted.version||"待确认版本",mode:"insensitive"}}});if(!version)version=await prisma.albumVersion.create({data:{albumId:target.id,name:extracted.version||"待确认版本",packageType:"待确认"}});
  const channel=await prisma.channel.upsert({where:{name:platform||input.source},update:{platform:platform||hostname(platformProductUrl)||input.source},create:{name:platform||input.source,platform:platform||hostname(platformProductUrl)||input.source,region:"待确认"}});
  const key=fingerprint(target.id,input.source,version.name,platformProductUrl||"");const pending=reasons.length>0,fanbar=extracted.saleType==="GROUP_ORDER"?extracted.price:null;const common={productPrice:extracted.price||0,fanbarPrice:fanbar,platformPrice:extracted.platformPrice||(!fanbar?extracted.price:null),offerSource:extracted.offerSource||input.source,purchasePlatform:platform,platformProductUrl,currency:extracted.currency||"CNY",saleType:extracted.saleType||"RETAIL",deadline:extracted.deadline?new Date(`${extracted.deadline}T00:00:00Z`):null,inclusions:JSON.stringify(extracted.benefits||[]),purchaseUrl:platformProductUrl,evidence:JSON.stringify({sourceUrl:input.sourceUrl,capturedAt:input.capturedAt||new Date().toISOString(),content:input.content.slice(0,5000),changeType:input.changeType,imageProvided:Boolean(input.image)}),confidence:extracted.confidence,status:pending?"PENDING_EXCEPTION" as const:"VERIFIED" as const,lastVerifiedAt:new Date()};const offer=await prisma.purchaseOffer.upsert({where:{fingerprint:key},update:common,create:{albumVersionId:version.id,channelId:channel.id,stockStatus:"UNKNOWN",shippingOrigin:"待确认",memberSelectable:false,sourceId:source.id,fingerprint:key,...common}});
  await prisma.priceHistory.create({data:{offerId:offer.id,price:offer.productPrice}});
  if(pending)await prisma.offerException.upsert({where:{offerId:offer.id},update:{reason:reasons.join("；"),rawPayload:JSON.stringify(input),status:"OPEN",reviewedAt:null},create:{offerId:offer.id,reason:reasons.join("；"),rawPayload:JSON.stringify(input)}});else await prisma.offerException.deleteMany({where:{offerId:offer.id}});
  await prisma.systemMetric.create({data:{metricName:"offer_ingestion",value:pending?0:1,unit:"status",metadata:JSON.stringify({source:input.source,pending})}}).catch(()=>{});
  return{offerId:offer.id,status:pending?"PENDING_EXCEPTION":"PUBLISHED",reasons,albumId:target.id};
 }
}
