import{SOURCES,businessHash,classifyChange,extractJsonLdProducts,isDue,nextAfter,retryAfterDate,serverBackoffHours,type BusinessItem,type SourceConfig,type SourceState}from"./core";

interface KV{get(key:string,type?:"json"):Promise<any>;put(key:string,value:string):Promise<void>}
interface Env{KPOP_MONITOR_STATE:KV;MYAREA_BASE_URL:string;KPOP_CALENDAR_URL:string;MYAREA_WEBHOOK_SECRET:string}
const USER_AGENT="KPOPPickMonitor/1.0 (+https://www.myarea.website)";
const stateKey=(id:string)=>`source:${id}`;const itemsKey=(id:string)=>`items:${id}`;

async function save(env:Env,source:SourceConfig,state:SourceState){await env.KPOP_MONITOR_STATE.put(stateKey(source.sourceId),JSON.stringify(state))}
async function fail(env:Env,source:SourceConfig,state:SourceState,status:number,response?:Response){const failures=(state.failureCount||0)+1;let next=nextAfter(serverBackoffHours(failures));if(status===429)next=retryAfterDate(response?.headers.get("retry-after")||null);const sourceStatus=failures>=3?"unavailable":source.status;await save(env,source,{...state,lastCheckedAt:new Date().toISOString(),nextCheckAt:next,failureCount:failures,sourceStatus})}
async function notifyCalendar(env:Env){const response=await fetch(`${env.MYAREA_BASE_URL}/api/calendar/sync`,{method:"POST",headers:{authorization:`Bearer ${env.MYAREA_WEBHOOK_SECRET}`}});if(!response.ok)throw new Error(`CALENDAR_WEBHOOK_${response.status}`)}
async function notifyOffer(env:Env,source:SourceConfig,change:{changeType:string;item:BusinessItem}){const item=change.item;const response=await fetch(`${env.MYAREA_BASE_URL}/api/offers/ingest`,{method:"POST",headers:{"content-type":"application/json","x-webhook-secret":env.MYAREA_WEBHOOK_SECRET},body:JSON.stringify({source:source.sourceId,sourceUrl:item.purchaseUrl,capturedAt:new Date().toISOString(),changeType:change.changeType,content:[`商品ID: ${item.productId}`,`商品名: ${item.title}`,item.artist&&`艺人: ${item.artist}`,item.album&&`专辑: ${item.album}`,item.version&&`版本: ${item.version}`,item.price!=null&&`价格: ${item.price} ${item.currency||""}`,item.benefit&&`特典: ${item.benefit}`,item.stock&&`库存: ${item.stock}`].filter(Boolean).join("\n")})});if(!response.ok)throw new Error(`OFFER_WEBHOOK_${response.status}`)}

async function runSource(env:Env,configured:SourceConfig){const source=configured.sourceId==="kpop-calendar"?{...configured,url:env.KPOP_CALENDAR_URL||configured.url}:configured;if(!source.enabled||source.fetchMode!=="fetch"||!source.url)return;const state=(await env.KPOP_MONITOR_STATE.get(stateKey(source.sourceId),"json")||{})as SourceState;if(!isDue(state))return;const headers:Record<string,string>={accept:source.sourceType==="calendar"?"application/json":"text/html", "user-agent":USER_AGENT};if(state.etag)headers["if-none-match"]=state.etag;if(state.lastModified)headers["if-modified-since"]=state.lastModified;let response:Response;try{response=await fetch(source.url,{headers,redirect:"follow"})}catch{await fail(env,source,state,503);return}if(response.status===304){await save(env,source,{...state,lastCheckedAt:new Date().toISOString(),lastSuccessfulAt:new Date().toISOString(),nextCheckAt:nextAfter(source.checkIntervalHours),failureCount:0,sourceStatus:"active"});return}if(response.status===403||response.status===429||response.status>=500){await fail(env,source,state,response.status,response);return}if(!response.ok){await fail(env,source,state,response.status,response);return}try{const body=await response.text();let items:BusinessItem[]=[];if(source.sourceType==="calendar"){const parsed=JSON.parse(body)as any;const events=Array.isArray(parsed)?parsed:Array.isArray(parsed.events)?parsed.events:[];items=events.filter((v:any)=>["comeback","release"].includes(v?.type)&&v?.confirmed===true).map((v:any)=>({productId:String(v.id||`${v.artist?.name||v.artist}-${v.date}-${v.title}`),title:String(v.title||""),artist:String(v.artist?.name||v.artist||""),album:String(v.title||""),purchaseUrl:String(v.source_url||source.url)}))}else items=extractJsonLdProducts(body,source.url);const hash=await businessHash(items),previousHash=state.lastHash,previous=(await env.KPOP_MONITOR_STATE.get(itemsKey(source.sourceId),"json")||[])as BusinessItem[];if(source.sourceType==="calendar"&&hash!==previousHash)await notifyCalendar(env);else if(previousHash&&hash!==previousHash)for(const change of classifyChange(previous,items))await notifyOffer(env,source,change);await env.KPOP_MONITOR_STATE.put(itemsKey(source.sourceId),JSON.stringify(items));await save(env,source,{lastHash:hash,lastCheckedAt:new Date().toISOString(),lastSuccessfulAt:new Date().toISOString(),nextCheckAt:nextAfter(source.checkIntervalHours),failureCount:0,etag:response.headers.get("etag")||undefined,lastModified:response.headers.get("last-modified")||undefined,lastProductIds:items.map(v=>v.productId),sourceStatus:"active"})}catch{await fail(env,source,state,503)}}
async function run(env:Env){await env.KPOP_MONITOR_STATE.put("health:workerLastRun",new Date().toISOString());for(const source of SOURCES)await runSource(env,source)}

export default{async scheduled(_controller:unknown,env:Env,ctx:{waitUntil(promise:Promise<unknown>):void}){ctx.waitUntil(run(env))},async fetch(request:Request,env:Env){const url=new URL(request.url);if(url.pathname==="/health")return Response.json({ok:true,workerLastRun:await env.KPOP_MONITOR_STATE.get("health:workerLastRun"),sources:SOURCES.map(({sourceId,status,checkIntervalHours,enabled})=>({sourceId,status,checkIntervalHours,enabled}))});if(url.pathname==="/run"&&request.headers.get("authorization")===`Bearer ${env.MYAREA_WEBHOOK_SECRET}`){await run(env);return Response.json({ok:true})}return new Response("Not found",{status:404})}};
