import{validAdminToken}from"@/lib/admin-session";import{NextRequest,NextResponse}from"next/server";import{z}from"zod";import{prisma}from"@/lib/prisma";import{PrismaDiscoveryRepository}from"@/lib/release-discovery";import{ReleaseVerificationService}from"@/lib/release-verification";import{normalizeAlias}from"@/lib/artist-alias";import{recordServerEvent}from"@/lib/analytics-store";
function denied(req:NextRequest){return!validAdminToken(req.cookies.get("kpop_admin")?.value)}
export async function GET(req:NextRequest){if(denied(req))return NextResponse.json({error:"UNAUTHORIZED"},{status:401});const data=await prisma.releaseCandidate.findMany({where:{verificationStatus:"CONFIRMED",status:{in:["NEEDS_REVIEW","DISCOVERED"]}},include:{evidenceItems:{orderBy:{collectedAt:"desc"}}},orderBy:{updatedAt:"desc"},take:100});return NextResponse.json({data})}
export async function PATCH(req:NextRequest){if(denied(req))return NextResponse.json({error:"UNAUTHORIZED"},{status:401});try{const body=z.object({id:z.string(),action:z.enum(["VERIFY","REJECT","RETRY","UPDATE"]),artistName:z.string().trim().min(1).max(200).optional(),albumName:z.string().trim().min(1).max(500).optional(),releaseDate:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),releaseType:z.string().max(50).optional(),adminNote:z.string().max(1000).optional()}).parse(await req.json());const row=await prisma.releaseCandidate.findUniqueOrThrow({where:{id:body.id}});
 if(body.action==="REJECT"){await prisma.releaseCandidate.update({where:{id:body.id},data:{status:"REJECTED",verificationStatus:"REJECTED",adminNote:body.adminNote,reviewedAt:new Date()}});recordServerEvent("release_candidate_rejected",{candidateId:body.id});return NextResponse.json({status:"REJECTED"})}
 if(body.action==="RETRY"){const result=await new ReleaseVerificationService().reverifyCandidate(body.id);return NextResponse.json({status:"RECHECKED",result})}
 if(body.action==="UPDATE"){const updated=await prisma.releaseCandidate.update({where:{id:body.id},data:{artistName:body.artistName,normalizedArtist:body.artistName?normalizeAlias(body.artistName):undefined,albumName:body.albumName,normalizedAlbum:body.albumName?normalizeAlias(body.albumName):undefined,releaseDate:body.releaseDate?new Date(`${body.releaseDate}T00:00:00Z`):undefined,releaseType:body.releaseType,adminNote:body.adminNote}});return NextResponse.json({status:"UPDATED",data:updated})}
 const aliases=JSON.parse(row.artistAliases)as string[],evidence=JSON.parse(row.evidence)as never[];const result=await new PrismaDiscoveryRepository().verifyCandidate({id:row.id,artistName:row.artistName,artistAliases:aliases,albumName:row.albumName,releaseDate:row.releaseDate.toISOString().slice(0,10),releaseType:row.releaseType,sourceName:row.sourceName,sourceUrl:row.sourceUrl,sourceType:undefined,coverImageUrl:row.coverImageUrl??undefined,sourcePublishedAt:row.sourcePublishedAt?.toISOString(),confidence:row.confidence,preorderStarted:row.preorderStarted??undefined,status:"VERIFIED",conflictReason:row.conflictReason,evidence});recordServerEvent("release_candidate_verified",{candidateId:body.id});return NextResponse.json({status:"VERIFIED",...result})
 }catch{return NextResponse.json({error:"INVALID_REQUEST"},{status:400})}}
